name: Run macro enhancement post-processor

on:
  push:
  workflow_dispatch:

jobs:
  process_macros:
    runs-on: ubuntu-latest
    name: Macro Enhancement
    env:
      LAYOUT_ID: ${{ secrets.LAYOUT_ID }} # this is just a secret to be easily reconfigured without a commit
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm install
      - name: Get ORYX layout
        run: npm run get
      - name: Process macros
        run: npm start
      - name: Compile QMK Firmware from source
        #run: qmk compile -kb moonlander -km neo
        uses: Phoscur/QMK-compile@main
        with:
          path: layout_src/moonlander_neophil-autobahn-fueled-wip_source
        
